# Generated by Django 5.1.2 on 2024-10-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_exam_visibility_mcqquestion_shortanswerquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
