# Generated by Django 5.1.2 on 2024-10-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_exam_question_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
