# Generated by Django 5.1.2 on 2024-10-18 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_exam_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
