# Generated by Django 5.1.2 on 2024-10-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_exam_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='', upload_to='profile_pictures/'),
        ),
    ]
