# Generated by Django 5.1.2 on 2024-10-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='attempt_no',
            field=models.IntegerField(default=0),
        ),
    ]
